# SwiftLint configuration for VaciPlayer

# Paths to include/exclude
included:
  - Sources
  - Tests

excluded:
  - .build
  - VaciPlayer.app
  - TempProject

# Rules configuration
disabled_rules:
  - trailing_whitespace # Can be annoying during development
  - todo # We allow TODO comments
  - type_name # Allow short type names like Song, PDF

opt_in_rules:
  - empty_count
  - first_where
  - sorted_first_last
  - contains_over_first_not_nil
  - explicit_init
  - redundant_nil_coalescing

# Rule customization
line_length:
  warning: 120
  error: 150
  ignores_comments: true

function_body_length:
  warning: 60
  error: 100

type_body_length:
  warning: 300
  error: 400

file_length:
  warning: 400
  error: 500

identifier_name:
  min_length:
    warning: 2
    error: 1
  max_length:
    warning: 40
    error: 50
  excluded:
    - id
    - x
    - y
    - i
    - j

# Custom rules
custom_rules:
  no_hardcoded_secrets:
    name: "No Hardcoded Secrets"
    regex: '(password|secret|key|token)\s*=\s*"[^"]*"'
    message: "Avoid hardcoding sensitive information"
    severity: error
    
  proper_spacing_operators:
    name: "Proper Spacing Around Operators"
    regex: '\w+[<>=!+\-*/%&|^]+\w+'
    message: "Operators should have spaces around them"
    severity: warning